version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: my-namespace/my-resource-class
    steps:
      - run: echo `ls /root/quanxiang_charts_staging/`
